services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "4983:4983"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - roketkr_app_network

networks:
  roketkr_app_network:
    external: true
